### ISSUE TITLE
Keeps poor time even flashed to MBC3 cartridge with RTC

### ISSUE THREAD

**Issue by jayjr1105** [pixjuan/clockboy#1]
Seems to be slow at time keeping, maybe behind 1-2 minutes per hour.  Am I doing something wrong or is it generating it's clock from the CPU?

**Comment by pixjuan** [comment]
Thanks for submitting this issue.
I did a quickfix to improve the accuracy, I did a one hour test and there was no drifting.
The clock is indeed generated by the CPU, or rather by the GameBoy's timer.
I started some code to use the RTC clock but I did not finish it, it is disabled right now.
I ordered an EZ Flash JR, so I will be able to add support for RTC in the future, which is a better long term solution.

**Comment by jayjr1105** [comment]
> Thanks for submitting this issue. I did a quickfix to improve the accuracy, I did a one hour test and there was no drifting. The clock is indeed generated by the CPU, or rather by the GameBoy's timer. I started some code to use the RTC clock but I did not finish it, it is disabled right now. I ordered an EZ Flash JR, so I will be able to add support for RTC in the future, which is a better long term solution.

Thanks, I'll try the new version soon. I'd also be willing to test a RTC release when ready.
